---
new_page_extension: md
auto_deploy: false
admin_path: "/static/_admin"
webhook_url: 
sections:
- type: heading
  label: Pages
- type: document
  path: assets/settings/pages/index.json
  label: Index
- type: document
  path: assets/settings/pages/volunteer.json
  label: Volunteer
- type: heading
  label: Global
- type: document
  path: assets/settings/intro_banner.json
  label: Banner Intro
- type: document
  path: assets/settings/global.json
  label: Settings
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: yarn
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry-preview
