---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url:
sections:
- type: heading
  label: Pages
- type: document
  path: assets/settings/pages/index.json
  label: Index
- type: heading
  label: Global
- type: document
  path: assets/settings/global.json
  label: Settings
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - NUXT_ENV_GMAPS_API_KEY=AIzaSyAMsspNc0oOOL0U_izPxQydt96-rD1lqi8
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run watch
