---
label: Global Settings
hide_body: true
fields:
- type: datetime
  name: copa_fest_date
  label: CopaFest Date
  description: When's the party?
- name: copa_fest_venue_name
  type: text
  config:
    required: true
  description: The name of the area where CopaFest will take place
  label: Venue Name
- name: copa_fest_venue_full_address
  type: text
  config:
    required: true
  label: Venue Address
  description: The full address (street, city, state, and zip) of where CopaFest will
    be held.
- type: datetime
  name: last_day_for_online_raffle_ticket_sale
  label: Online Raffle Ticket Cut-Off
  description: Online sales are unavailable after this date and time.
- type: textarea
  name: donation_pitch
  label: Donation Pitch
  description: Why should someone consider donating to the club?
  config:
    wysiwyg: true
    schema:
      format: markdown
    required: false
- name: notifications
  type: field_group_list
  fields:
  - name: type
    type: select
    default: Danger
    config:
      required: false
      options:
      - Danger
      - Warning
      - Success
      source:
        type: simple
        section: 
        file: 
        path: 
    label: Type
    description: The type of notification. Defaults to Danger.<br><br>Danger = Red<br>Warning
      = Yellow<br>Success = Green
  - name: text
    type: textarea
    default: ''
    config:
      required: true
      wysiwyg: true
      schema:
        format: html
    description: The text of the notification.
    label: Text
  config:
    min: 
    max: 
    labelField: 
  description: Text to display beneath the navbar on every page.
  label: Notifications
pages:
- assets/settings/global.json
